### PR TITLE
refactor(OMN-14490): graduate canonical ModelNodeIntrospectionEvent + nested DTOs to omnibase_core (additive)

### PR DESCRIPTION
**Pull request by jonahgabriel**
## OMN-14490 — graduate the canonical node-introspection wire event to omnibase_core (ADDITIVE, core-first)

**Refs OMN-14490** (reference pattern for the broader duplicate-model consolidation, Task #38).

### Problem
`node-introspection.v1` (HW≈23881, very hot) had TWO `ModelNodeIntrospectionEvent` definitions:
the rich `omnibase_infra` producer event vs a slim per-repo `extra="ignore"` consumer copy in
omnimarket `node_projection_registration` that **silently dropped** `endpoints` /
`declared_capabilities` / `discovered_capabilities` / `contract_capabilities` / `current_state`.
Silent field-dropping across a live seam is the OMN-14485/14490 class.

### What this PR does (additive only — no infra copies deleted)
Graduates the shared wire event + its full nested closure into **omnibase_core** as the single
canonical home (it references core domain types — `EnumNodeKind`, `ModelContractCapabilities`,
`ModelSemVer`, `ModelFeatureFlags` — so it CANNOT live in compat; that would invert compat→core).

Canonical import paths (final — codemod lane targets these):
- `omnibase_core.models.registration.model_node_introspection_event.ModelNodeIntrospectionEvent`
- `omnibase_core.models.registration` also exports the 7 nested DTOs:
  `ModelNodeCapabilities`, `ModelDiscoveredCapabilities`, `ModelNodeEventBusConfig`,
  `ModelNodeMetadata`, `ModelMCPContractConfig`, `ModelEventBusTopicEntry`,
  `ModelIntrospectionPerformanceMetrics`
- `omnibase_core.enums.EnumIntrospectionReason` (was `omnibase_infra.enums`)

Design decisions:
- Canonical event uses **`extra="forbid"`** (fail LOUD on unmodeled fields) — the operator directive;
  `extra="ignore"` on the slim consumer is exactly what made this silent. Safe now because producer +
  consumer share the ONE model.
- The two shared field validators are wired to **core single-source utilities**: reuse existing
  `omnibase_core.utils.util_validators.ensure_timezone_aware`; add `validate_endpoint_urls_dict`
  to the same module. Zero `omnibase_infra` dependency in the graduated closure.
- `ModelNodeCapabilities` keeps `extra="allow"` by design (custom capabilities via `model_extra`).

### dod_evidence
- New cross-boundary regression test `tests/unit/models/registration/test_model_node_introspection_event.py`
  (4 tests): rich fields survive the JSON wire round-trip; `extra="forbid"` RAISES on an unknown wire
  key (RED against exists-but-wrong = the slim `extra="ignore"` drop); naive-timestamp + malformed-URL
  rejected (validators wired). All 4 GREEN.
- `uv run mypy src/omnibase_core/models/registration/ src/omnibase_core/utils/util_validators.py src/omnibase_core/enums/enum_introspection_reason.py` → **Success: no issues found in 13 source files**.
- `uv run ruff format/check` clean.
- Regression: `tests/unit/models/registration/` + `tests/unit/models/discovery/` → **71 passed, 1 skipped** (additive `__init__`/util/enum edits break nothing).

### Landing order (Codex — core FIRST)
1. **THIS core PR → dev** (additive; core lands green independently, no window where infra is broken).
2. **infra child PR**: repoint the producer + delete infra copies + update ~83 call-sites to the core
   canonical paths (mechanical **codemod lane**, prepared against this worktree, LANDS AFTER core).
3. **omnimarket child PR**: delete the slim consumer copy; consume the canonical core model.

### Follow-ups (NOT in this PR)
- Discovery service-discovery `ModelNodeIntrospectionEvent` rename (`ModelNodeDiscoveryAnnouncement`)
  + twin-kill: incoming as commit 2 on this branch.
- Two same-name-different-module pairs surfaced by graduation (`ModelNodeCapabilities`,
  `ModelNodeMetadata` in `discovery`/`core` vs new `registration`) → tracked under Task #38 consolidation.

**Draft — do not merge.** OCC evidence companion owed from a non-implementer verifier (implementer must
not self-author OCC evidence).

### CODE REVIEW

**Comment by jonahgabriel** [comment]
Closing as **superseded**. This PR graduates the introspection event to core to resolve OMN-14490, but OMN-14490 was addressed a different way by omnimarket#1732 (MERGED 2026-07-13T04:26Z, "consume canonical registration event models"), which imports the omnibase_infra models directly (legal top-layer import) rather than graduating the event — making this approach unnecessary. It also carried an unresolved import-ratchet red and no OCC companion. Reversible: reopen if the broader duplicate-model consolidation later decides it does want the core-graduation. Closed autonomously per operator go (2026-07-16).
